# Generated by Django 5.0.6 on 2024-10-05 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khat_owner_name', models.CharField(max_length=255)),
                ('khat_type', models.CharField(choices=[('qudaa', 'Qudaa'), ('urata', 'Urata'), ('Qarxii', 'Qarxii')], max_length=200)),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedBono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trader_signature', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bono', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='generated_bonos', to='bono.bono')),
            ],
        ),
    ]
